(()=>{
'use strict';
let context=null,master=null,sfxBus=null,musicBus=null,unlocked=false,playing=false,musicTimer=0,nextMusicTime=0,musicStep=0,intensity=0;
let settings={masterVolume:.8,musicEnabled:false,sfxEnabled:true,musicVolume:.34,sfxVolume:.72};
const activeMusic=new Set(),BPM=96,EIGHTH=60/BPM/2;
const CHORDS=Object.freeze([[110,130.81,164.81,220],[87.31,110,130.81,164.81],[65.41,98,130.81,164.81],[98,123.47,146.83,196]]);
const PATTERNS=Object.freeze({jump:[[420,.07,'square',1]],doubleJump:[[620,.08,'triangle',1],[820,.06,'sine',.55,.045]],slide:[[185,.08,'square',.7]],dash:[[150,.14,'sawtooth',.8]],collect:[[760,.04,'sine',.48]],shield:[[230,.15,'square',.8],[460,.1,'sine',.45,.04]],perfect:[[980,.045,'triangle',.65],[1240,.035,'sine',.5,.038]],fail:[[90,.34,'sawtooth',1]],newRecord:[[660,.12,'triangle',.7],[880,.14,'triangle',.75,.11],[1100,.22,'sine',.7,.24]],overdrive:[[620,.16,'square',.7],[920,.18,'sawtooth',.65,.07]],powerup:[[860,.15,'triangle',.7]],break:[[150,.08,'sawtooth',.75]],checkpoint:[[580,.14,'sine',.55]]});
function ensure(){if(context)return true;try{const AudioCtor=window.AudioContext||window.webkitAudioContext;if(!AudioCtor)return false;context=new AudioCtor();master=context.createGain();sfxBus=context.createGain();musicBus=context.createGain();master.gain.value=settings.masterVolume;sfxBus.gain.value=settings.sfxVolume;musicBus.gain.value=0;sfxBus.connect(master);musicBus.connect(master);master.connect(context.destination);return true}catch(e){return false}}
async function unlock(){if(!ensure())return false;try{if(context.state==='suspended')await context.resume();unlocked=context.state==='running';if(unlocked&&playing)startMusic();return unlocked}catch(e){return false}}
function tone(freq=440,d=.06,type='sine',vol=.035,delay=0,category='sfx'){if(!unlocked||!ensure())return;const enabled=category==='music'?settings.musicEnabled:settings.sfxEnabled;if(!enabled)return;const now=context.currentTime+delay,o=context.createOscillator(),g=context.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(Math.max(45,freq*.72),now+d);g.gain.setValueAtTime(Math.max(.0001,vol),now);g.gain.exponentialRampToValueAtTime(.0001,now+d);o.connect(g).connect(category==='music'?musicBus:sfxBus);o.start(now);o.stop(now+d+.02)}
function sfx(name){const pattern=PATTERNS[name];if(!pattern)return;for(const item of pattern)tone(item[0],item[1],item[2],.055*(item[3]||1),item[4]||0,'sfx')}
function custom(freq,d,type,vol){tone(freq,d,type,vol,0,'sfx')}
function remember(node){activeMusic.add(node);node.addEventListener('ended',()=>activeMusic.delete(node),{once:true});return node}
function padVoice(freq,start,duration,volume,type){const o=remember(context.createOscillator()),filter=context.createBiquadFilter(),g=context.createGain();o.type=type;o.frequency.setValueAtTime(freq,start);o.detune.value=(Math.random()-.5)*5;filter.type='lowpass';filter.frequency.value=920;filter.Q.value=.6;g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(volume,start+.34);g.gain.setValueAtTime(volume,start+Math.max(.4,duration-.52));g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(filter).connect(g).connect(musicBus);o.start(start);o.stop(start+duration+.03)}
function pluck(freq,start,volume=.012){const o=remember(context.createOscillator()),filter=context.createBiquadFilter(),g=context.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,start);filter.type='lowpass';filter.frequency.setValueAtTime(1500,start);filter.frequency.exponentialRampToValueAtTime(520,start+.28);g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(volume,start+.018);g.gain.exponentialRampToValueAtTime(.0001,start+.3);o.connect(filter).connect(g).connect(musicBus);o.start(start);o.stop(start+.33)}
function softKick(start){const o=remember(context.createOscillator()),g=context.createGain();o.type='sine';o.frequency.setValueAtTime(76,start);o.frequency.exponentialRampToValueAtTime(43,start+.16);g.gain.setValueAtTime(.028,start);g.gain.exponentialRampToValueAtTime(.0001,start+.2);o.connect(g).connect(musicBus);o.start(start);o.stop(start+.22)}
function softHat(start){const length=Math.max(1,Math.floor(context.sampleRate*.045)),buffer=context.createBuffer(1,length,context.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);const source=remember(context.createBufferSource()),filter=context.createBiquadFilter(),g=context.createGain();source.buffer=buffer;filter.type='highpass';filter.frequency.value=5200;g.gain.setValueAtTime(.005,start);g.gain.exponentialRampToValueAtTime(.0001,start+.045);source.connect(filter).connect(g).connect(musicBus);source.start(start);source.stop(start+.05)}
function scheduleStep(step,start){const chordIndex=Math.floor(step/8)%CHORDS.length,local=step%8,chord=CHORDS[chordIndex];if(local===0)for(let i=0;i<chord.length;i++)padVoice(chord[i],start,EIGHTH*7.7,i===0?.012:.008,i%2?'sine':'triangle');if(local===0||local===4){pluck(chord[0]/2,start,.026);softKick(start)}else if(local===2||local===6)softHat(start);if(local%2===1){const order=[1,2,3,2],note=chord[order[(Math.floor(local/2)+chordIndex)%order.length]]*2;pluck(note,start,.007)}if(intensity>0){if(local%2===0)softKick(start+.015);if(local===3||local===7)pluck(chord[2]*2,start,.012)}}
function scheduler(){if(!playing||!settings.musicEnabled||!unlocked||!context)return;while(nextMusicTime<context.currentTime+.28){scheduleStep(musicStep++,nextMusicTime);nextMusicTime+=EIGHTH}}
function startMusic(){if(musicTimer||!playing||!settings.musicEnabled||!unlocked||!ensure())return;musicBus.gain.cancelScheduledValues(context.currentTime);musicBus.gain.setValueAtTime(Math.max(.0001,musicBus.gain.value),context.currentTime);musicBus.gain.linearRampToValueAtTime(settings.musicVolume,context.currentTime+.45);nextMusicTime=context.currentTime+.08;musicStep=0;scheduler();musicTimer=setInterval(scheduler,100)}
function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=0}if(context&&musicBus){musicBus.gain.cancelScheduledValues(context.currentTime);musicBus.gain.setValueAtTime(musicBus.gain.value,context.currentTime);musicBus.gain.linearRampToValueAtTime(0,context.currentTime+.08);for(const node of activeMusic)try{node.stop(context.currentTime+.1)}catch(e){}activeMusic.clear()}}
function setPlaying(value){playing=!!value;if(playing)startMusic();else stopMusic()}
function setIntensity(value){intensity=value==='overload'||value===1?1:0}
function setSettings(next){settings={...settings,...next};if(master)master.gain.value=Math.max(0,Math.min(1,settings.masterVolume));if(sfxBus)sfxBus.gain.value=settings.sfxEnabled?Math.max(0,Math.min(1,settings.sfxVolume)):0;if(musicBus&&musicTimer)musicBus.gain.setTargetAtTime(Math.max(0,Math.min(1,settings.musicVolume)),context.currentTime,.12);if(!settings.musicEnabled)stopMusic();else if(playing)startMusic()}
function dispose(){stopMusic();if(context){try{context.close()}catch(e){}}context=null;master=null;sfxBus=null;musicBus=null;unlocked=false}
globalThis.NovaRunAudio=Object.freeze({unlock,sfx,custom,setPlaying,setIntensity,setSettings,dispose,get unlocked(){return unlocked}});
})();
