(()=>{
'use strict';
const I18N={
    zh:{gameLabel:'多场景跑酷游戏',canvasLabel:'跑酷游戏画面：躲避障碍，收集能量并尽可能跑得更远',touch:'触摸控制',language:'语言',difficulty:'难度',scene:'场景',guangzhou:'广州·珠江新城',shanghai:'上海·陆家嘴',shenzhen:'深圳·未来 CBD',snow:'雪山之巅',volcano:'熔岩火山',jiuzhaigou:'九寨沟',sceneRun:'穿越 {scene}',rotate:'手机横屏体验更佳',landscape:'横屏',portrait:'竖屏',switchLandscape:'切换到横屏',switchPortrait:'切换到竖屏',rotateLandscapeHint:'请旋转手机切换到横屏',rotatePortraitHint:'请旋转手机切换到竖屏',easy:'低难度',medium:'中难度',hard:'高难度',jump:'跳跃',slide:'滑铲',dash:'冲刺',distance:'距离',combo:'连击',energy:'能量',overdrive:'超载',shield:'护盾',magnet:'磁力',slow:'缓速',shieldOn:'护盾上线',magnetOn:'磁力全开',slowOn:'时间减速',shieldBlock:'护盾抵消',overdriveOn:'超载冲刺',systemOffline:'电子机关已关闭',perfect:'完美闪避 +{score}',features:'二段跳 · 滑铲 · 冲刺破障 · 完美闪避',start:'开始奔跑',controls:'空格/W 跳跃 · S 滑铲 · Shift/K 冲刺',paused:'已暂停',resume:'按 P 或 Esc 继续',gameOver:'本次奔跑结束',points:'{score} 分',result:'距离 {distance} m · 最高分 {best}',again:'再来一局'},
    en:{gameLabel:'Multi-scene parkour game',canvasLabel:'Parkour game: dodge hazards, collect energy, and run as far as possible',touch:'Touch controls',language:'Language',difficulty:'Difficulty',scene:'Scene',guangzhou:'Guangzhou · Zhujiang New Town',shanghai:'Shanghai · Lujiazui',shenzhen:'Shenzhen · Future CBD',snow:'Snow Summit',volcano:'Lava Volcano',jiuzhaigou:'Jiuzhaigou Valley',sceneRun:'Run through {scene}',rotate:'Landscape recommended on phones',landscape:'Landscape',portrait:'Portrait',switchLandscape:'Switch to landscape',switchPortrait:'Switch to portrait',rotateLandscapeHint:'Rotate your phone to landscape',rotatePortraitHint:'Rotate your phone to portrait',easy:'Easy',medium:'Medium',hard:'Hard',jump:'Jump',slide:'Slide',dash:'Dash',distance:'Distance',combo:'Combo',energy:'Energy',overdrive:'Overdrive',shield:'Shield',magnet:'Magnet',slow:'Slow',shieldOn:'Shield online',magnetOn:'Magnet active',slowOn:'Time slowed',shieldBlock:'Shield saved you',overdriveOn:'Overdrive!',systemOffline:'Electronic hazard disabled',perfect:'Perfect dodge +{score}',features:'Double jump · Slide · Smash dash · Perfect dodge',start:'Start running',controls:'Space/W Jump · S Slide · Shift/K Dash',paused:'Paused',resume:'Press P or Esc to resume',gameOver:'Run complete',points:'{score} pts',result:'Distance {distance} m · Best {best}',again:'Run again'},
    ru:{gameLabel:'Паркур с разными локациями',canvasLabel:'Паркур: уклоняйтесь от препятствий, собирайте энергию и бегите как можно дальше',touch:'Сенсорное управление',language:'Язык',difficulty:'Сложность',scene:'Локация',guangzhou:'Гуанчжоу · Чжуцзян',shanghai:'Шанхай · Луцзяцзуй',shenzhen:'Шэньчжэнь · CBD будущего',snow:'Снежная вершина',volcano:'Лавовый вулкан',jiuzhaigou:'Долина Цзючжайгоу',sceneRun:'Маршрут: {scene}',rotate:'На телефоне лучше играть горизонтально',landscape:'Альбом',portrait:'Портрет',switchLandscape:'Перейти в альбомный режим',switchPortrait:'Перейти в портретный режим',rotateLandscapeHint:'Поверните телефон горизонтально',rotatePortraitHint:'Поверните телефон вертикально',easy:'Легко',medium:'Средне',hard:'Сложно',jump:'Прыжок',slide:'Подкат',dash:'Рывок',distance:'Дистанция',combo:'Комбо',energy:'Энергия',overdrive:'Перегрузка',shield:'Щит',magnet:'Магнит',slow:'Замедление',shieldOn:'Щит активирован',magnetOn:'Магнит активирован',slowOn:'Время замедлено',shieldBlock:'Щит спас вас',overdriveOn:'Перегрузка!',systemOffline:'Электронная преграда отключена',perfect:'Идеальный манёвр +{score}',features:'Двойной прыжок · Подкат · Рывок · Идеальный манёвр',start:'Начать забег',controls:'Пробел/W — прыжок · S — подкат · Shift/K — рывок',paused:'Пауза',resume:'P или Esc — продолжить',gameOver:'Забег завершён',points:'{score} очк.',result:'Дистанция {distance} м · Рекорд {best}',again:'Ещё раз'}
  };
Object.assign(I18N.zh,{dreamPeak:'晨雾折光峰',left:'向左移动',right:'向右移动',platformFeatures:'手工平台关 · 移动机关 · 检查点 · 隐藏路线',platformControls:'A/D 或 ←/→ 移动 · 空格跳跃 · Shift 冲刺',checkpointRespawn:'已在最近检查点复活',checkpointOn:'检查点已激活',gateOpen:'机关已开启',secretFound:'发现隐藏山脊',levelComplete:'登顶成功'});
Object.assign(I18N.en,{dreamPeak:'Dreammist Prism Peak',left:'Move left',right:'Move right',platformFeatures:'Hand-built level · Moving mechanisms · Checkpoints · Secret route',platformControls:'A/D or ←/→ Move · Space Jump · Shift Dash',checkpointRespawn:'Respawned at the latest checkpoint',checkpointOn:'Checkpoint activated',gateOpen:'Mechanism activated',secretFound:'Hidden ridge discovered',levelComplete:'Summit reached'});
Object.assign(I18N.ru,{dreamPeak:'Пик призрачного тумана',left:'Двигаться влево',right:'Двигаться вправо',platformFeatures:'Ручной уровень · Механизмы · Точки · Тайный путь',platformControls:'A/D или ←/→ — движение · Пробел — прыжок · Shift — рывок',checkpointRespawn:'Возврат к последней точке',checkpointOn:'Контрольная точка активна',gateOpen:'Механизм активирован',secretFound:'Найден скрытый путь',levelComplete:'Вершина достигнута'});
Object.assign(I18N.zh,{settings:'游戏设置',reduceMotion:'减少动态效果',jumpCue:'跳跃',slideCue:'滑铲',dashCue:'冲刺',bestLabel:'最高纪录',newBest:'新纪录',runSummary:'本局表现',motionReduced:'动态效果已减少'});
Object.assign(I18N.en,{settings:'Game settings',reduceMotion:'Reduce motion',jumpCue:'Jump',slideCue:'Slide',dashCue:'Dash',bestLabel:'Best',newBest:'New best',runSummary:'Run summary',motionReduced:'Motion reduced'});
Object.assign(I18N.ru,{settings:'Настройки',reduceMotion:'Меньше движения',jumpCue:'Прыжок',slideCue:'Подкат',dashCue:'Рывок',bestLabel:'Рекорд',newBest:'Новый рекорд',runSummary:'Итоги забега',motionReduced:'Движение уменьшено'});
Object.assign(I18N.zh,{skin:'角色外观',music:'背景音乐',sfx:'游戏音效',vibration:'震动',showTutorial:'显示教程',highContrast:'高对比度',masterVolume:'总音量',musicVolume:'音乐音量',sfxVolume:'音效音量',shakeStrength:'屏幕震动强度',touchOpacity:'触控按钮透明度',clearSave:'清除存档',progress:'成长记录',dailyTasks:'每日任务',achievements:'成就',skipTutorial:'跳过教程',backMenu:'返回菜单',changeScene:'更换场景',shareScore:'分享成绩',clearConfirmTitle:'确定清除存档？',clearConfirmText:'所有统计、成就、解锁和设置都会被删除，无法恢复。',cancel:'取消',confirmClear:'确认清除',locked:'未解锁',totalDistance:'总奔跑距离',totalRuns:'总游戏局数',highestCombo:'最高连击',totalCollects:'总收集数量',daily_distance:'累计跑 {target} 米',daily_perfect:'完成 {target} 次完美闪避',daily_breaks:'冲刺破坏 {target} 个障碍',achievement_firstRun:'初次启程',achievement_distance5k:'长跑新星',achievement_collector100:'能量收藏家',achievement_combo10:'十连高手',achievement_breaker25:'破障专家',achievement_daily3:'今日全勤',skin_nova:'新星蓝',skin_pulse:'脉冲绿',skin_sunset:'落日橙',skin_prism:'棱镜紫',skin_ace:'极光王牌',tutorialJumpTitle:'先试试跳跃',tutorialJumpText:'按空格、W、↑ 或“跳跃”按钮。',tutorialSlideTitle:'从低处滑过',tutorialSlideText:'按住 S、↓ 或“滑铲”按钮。',tutorialDoubleTitle:'接着完成二段跳',tutorialDoubleText:'离地后再次按跳跃。',tutorialDashTitle:'用冲刺破坏障碍',tutorialDashText:'遇到可破坏障碍时按 Shift、K 或冲刺。',tutorialCollectTitle:'收集能量',tutorialCollectText:'碰到发光能量币，为冲刺充能。',tutorialComplete:'简短教程完成',tutorialSkipped:'已跳过教程',scoreCopied:'成绩和挑战链接已复制',copyFailed:'复制失败，请手动复制地址栏链接',shareTemplate:'我在 NOVA RUN 的{scene}跑了{distance}米，拿到{score}分，你能超过我吗？',sceneUnlocked:'新场景已解锁：{name}',skinUnlocked:'新外观已解锁：{name}'});
Object.assign(I18N.en,{skin:'Runner style',music:'Background music',sfx:'Sound effects',vibration:'Vibration',showTutorial:'Show tutorial',highContrast:'High contrast',masterVolume:'Master volume',musicVolume:'Music volume',sfxVolume:'Effects volume',shakeStrength:'Screen shake',touchOpacity:'Touch opacity',clearSave:'Clear save data',progress:'Progress',dailyTasks:'Daily tasks',achievements:'Achievements',skipTutorial:'Skip tutorial',backMenu:'Main menu',changeScene:'Change scene',shareScore:'Share score',clearConfirmTitle:'Clear save data?',clearConfirmText:'All stats, achievements, unlocks, and settings will be permanently removed.',cancel:'Cancel',confirmClear:'Clear everything',locked:'Locked',totalDistance:'Total distance',totalRuns:'Runs played',highestCombo:'Highest combo',totalCollects:'Total collected',daily_distance:'Run {target} m total',daily_perfect:'Make {target} perfect dodges',daily_breaks:'Dash-break {target} hazards',achievement_firstRun:'First run',achievement_distance5k:'Distance star',achievement_collector100:'Energy collector',achievement_combo10:'Combo ten',achievement_breaker25:'Barrier breaker',achievement_daily3:'Daily sweep',skin_nova:'Nova blue',skin_pulse:'Pulse green',skin_sunset:'Sunset orange',skin_prism:'Prism violet',skin_ace:'Aurora ace',tutorialJumpTitle:'Start with a jump',tutorialJumpText:'Press Space, W, ↑, or the Jump button.',tutorialSlideTitle:'Slide under low hazards',tutorialSlideText:'Hold S, ↓, or the Slide button.',tutorialDoubleTitle:'Now double jump',tutorialDoubleText:'Press jump again while airborne.',tutorialDashTitle:'Dash through a hazard',tutorialDashText:'Use Shift, K, or Dash on a breakable hazard.',tutorialCollectTitle:'Collect energy',tutorialCollectText:'Touch glowing energy coins to recharge dash.',tutorialComplete:'Quick tutorial complete',tutorialSkipped:'Tutorial skipped',scoreCopied:'Score and challenge link copied',copyFailed:'Copy failed; copy the address-bar link manually',shareTemplate:'I ran {distance} m in NOVA RUN — {scene} and scored {score}. Can you beat me?',sceneUnlocked:'New scene unlocked: {name}',skinUnlocked:'New style unlocked: {name}'});
Object.assign(I18N.ru,{skin:'Стиль героя',music:'Фоновая музыка',sfx:'Звуковые эффекты',vibration:'Вибрация',showTutorial:'Показывать обучение',highContrast:'Высокий контраст',masterVolume:'Общая громкость',musicVolume:'Громкость музыки',sfxVolume:'Громкость эффектов',shakeStrength:'Тряска экрана',touchOpacity:'Прозрачность кнопок',clearSave:'Удалить сохранение',progress:'Прогресс',dailyTasks:'Задания дня',achievements:'Достижения',skipTutorial:'Пропустить обучение',backMenu:'Главное меню',changeScene:'Сменить локацию',shareScore:'Поделиться',clearConfirmTitle:'Удалить сохранение?',clearConfirmText:'Статистика, достижения, открытия и настройки будут удалены навсегда.',cancel:'Отмена',confirmClear:'Удалить всё',locked:'Закрыто',totalDistance:'Общая дистанция',totalRuns:'Забегов',highestCombo:'Лучшее комбо',totalCollects:'Всего собрано',daily_distance:'Пробежать {target} м',daily_perfect:'Сделать {target} идеальных манёвров',daily_breaks:'Разбить рывком {target} препятствия',achievement_firstRun:'Первый забег',achievement_distance5k:'Звезда дистанции',achievement_collector100:'Сборщик энергии',achievement_combo10:'Комбо десять',achievement_breaker25:'Разрушитель',achievement_daily3:'Все задания дня',skin_nova:'Нова-синий',skin_pulse:'Импульс-зелёный',skin_sunset:'Закат-оранжевый',skin_prism:'Призма-фиолетовый',skin_ace:'Аврора-ас',tutorialJumpTitle:'Сначала прыжок',tutorialJumpText:'Пробел, W, ↑ или кнопка прыжка.',tutorialSlideTitle:'Подкат под преградой',tutorialSlideText:'Удерживайте S, ↓ или кнопку подката.',tutorialDoubleTitle:'Теперь двойной прыжок',tutorialDoubleText:'Нажмите прыжок ещё раз в воздухе.',tutorialDashTitle:'Разбейте преграду рывком',tutorialDashText:'Используйте Shift, K или кнопку рывка.',tutorialCollectTitle:'Соберите энергию',tutorialCollectText:'Касайтесь светящихся монет для заряда.',tutorialComplete:'Обучение завершено',tutorialSkipped:'Обучение пропущено',scoreCopied:'Результат и ссылка скопированы',copyFailed:'Не удалось скопировать; используйте адресную строку',shareTemplate:'Я пробежал {distance} м в NOVA RUN — {scene} и набрал {score}. Сможешь лучше?',sceneUnlocked:'Открыта локация: {name}',skinUnlocked:'Открыт стиль: {name}'});
Object.assign(I18N.zh,{selectedRoute:'当前路线',runMode:'模式',parkourMode:'跑酷挑战',enterRoute:'进入路线'});
Object.assign(I18N.en,{selectedRoute:'Selected route',runMode:'Mode',parkourMode:'Parkour challenge',enterRoute:'Enter route'});
Object.assign(I18N.ru,{selectedRoute:'Выбранный маршрут',runMode:'Режим',parkourMode:'Паркур',enterRoute:'Войти на маршрут'});
Object.assign(I18N.zh,{achievementUnlocked:'成就已解锁：{name}'});Object.assign(I18N.en,{achievementUnlocked:'Achievement unlocked: {name}'});Object.assign(I18N.ru,{achievementUnlocked:'Открыто достижение: {name}'});
Object.assign(I18N.zh,{performanceMode:'性能模式',performanceAuto:'自动调节',performanceQuality:'画质优先',performanceFast:'流畅优先',novaReady:'NOVA 核心就绪',novaReadyHint:'按冲刺释放超载',novaFlow:'NOVA FLOW',novaRescue:'NOVA 救援',shieldRescue:'护盾救援',challengeGrade:'闯关评级',completionTime:'完成时间',deaths:'死亡次数',hiddenRoute:'隐藏路线',badgeAllCollects:'全收集',badgeNoDeaths:'零死亡',badgeTime:'限时完成'});
Object.assign(I18N.en,{performanceMode:'Performance',performanceAuto:'Automatic',performanceQuality:'Quality',performanceFast:'Smooth',novaReady:'NOVA CORE READY',novaReadyHint:'Dash to release Overload',novaFlow:'NOVA FLOW',novaRescue:'NOVA RESCUE',shieldRescue:'SHIELD RESCUE',challengeGrade:'Stage grade',completionTime:'Time',deaths:'Deaths',hiddenRoute:'Hidden route',badgeAllCollects:'All collected',badgeNoDeaths:'No deaths',badgeTime:'Time badge'});
Object.assign(I18N.ru,{performanceMode:'Производительность',performanceAuto:'Авто',performanceQuality:'Качество',performanceFast:'Плавность',novaReady:'ЯДРО NOVA ГОТОВО',novaReadyHint:'Рывок включает перегрузку',novaFlow:'NOVA FLOW',novaRescue:'СПАСЕНИЕ NOVA',shieldRescue:'СПАСЕНИЕ ЩИТОМ',challengeGrade:'Рейтинг этапа',completionTime:'Время',deaths:'Смерти',hiddenRoute:'Скрытый путь',badgeAllCollects:'Всё собрано',badgeNoDeaths:'Без смертей',badgeTime:'На время'});
Object.assign(I18N.zh,{signature_guangzhou:'珠江跨桥连段',signature_shanghai:'陆家嘴列车穿梭',signature_shenzhen:'未来扫描破障链',signature_snow:'雪崩冰脊追逐',signature_volcano:'熔岩逃生节拍',signature_jiuzhaigou:'瀑布踏水连跃'});
Object.assign(I18N.en,{signature_guangzhou:'RIVER BRIDGE FLOW',signature_shanghai:'LUJIAZUI TRAIN RUSH',signature_shenzhen:'SCAN BREAK CHAIN',signature_snow:'AVALANCHE RIDGE',signature_volcano:'LAVA ESCAPE RHYTHM',signature_jiuzhaigou:'WATERFALL STEP FLOW'});
Object.assign(I18N.ru,{signature_guangzhou:'СЕРИЯ НАД РЕКОЙ',signature_shanghai:'РЫВОК СКВОЗЬ ПОЕЗДА',signature_shenzhen:'ЦЕПЬ СКАНЕРОВ',signature_snow:'ЛАВИННЫЙ ХРЕБЕТ',signature_volcano:'РИТМ ПОБЕГА ОТ ЛАВЫ',signature_jiuzhaigou:'ПРЫЖКИ У ВОДОПАДА'});
Object.assign(I18N.zh,{tutorialTryAgain:'再试一次，路线已保护',tutorialOverload:'NOVA 核心即将充满：按冲刺释放超载'});
Object.assign(I18N.en,{tutorialTryAgain:'Try again — tutorial route protected',tutorialOverload:'NOVA core full: Dash to release Overload'});
Object.assign(I18N.ru,{tutorialTryAgain:'Попробуйте ещё раз — маршрут защищён',tutorialOverload:'Ядро NOVA заполнено: рывок включает перегрузку'});
Object.assign(I18N.zh,{mapsTab:'地图',characterTab:'角色',settingsTab:'设置'});Object.assign(I18N.en,{mapsTab:'Maps',characterTab:'Runner',settingsTab:'Settings'});Object.assign(I18N.ru,{mapsTab:'Карты',characterTab:'Герой',settingsTab:'Настройки'});
Object.assign(I18N.zh,{theme:'显示模式',darkMode:'暗夜模式',lightMode:'日间模式'});Object.assign(I18N.en,{theme:'Display mode',darkMode:'Night mode',lightMode:'Day mode'});Object.assign(I18N.ru,{theme:'Режим экрана',darkMode:'Ночной режим',lightMode:'Дневной режим'});
Object.assign(I18N.zh,{shareFallbackTitle:'分享挑战',manualCopy:'当前浏览器不能直接调用系统分享，请复制下面的成绩和挑战链接。',copyShare:'复制内容',close:'关闭',manualCopySelected:'内容已选中，请长按或按 Ctrl+C 复制'});Object.assign(I18N.en,{shareFallbackTitle:'Share challenge',manualCopy:'System sharing is unavailable here. Copy the score and challenge link below.',copyShare:'Copy content',close:'Close',manualCopySelected:'Text selected — long-press or press Ctrl+C to copy'});Object.assign(I18N.ru,{shareFallbackTitle:'Поделиться',manualCopy:'Системная отправка недоступна. Скопируйте результат и ссылку ниже.',copyShare:'Копировать',close:'Закрыть',manualCopySelected:'Текст выделен — удерживайте или нажмите Ctrl+C'});
Object.assign(I18N.zh,{mapSelection:'地图选择',mapSelectionHint:'选择图片查看路线与专属机关',endlessMode:'无尽跑酷',endlessModeHint:'六座城市与自然场景',challengeMode:'闯关模式',challengeModeHint:'手工平台关卡',challengeBadge:'独立关卡',parkourMode:'无尽跑酷',stageMode:'关卡闯关',startChallenge:'开始闯关',preview_guangzhou:'江畔塔影 · 无人机与桥梁',preview_shanghai:'高速列车 · 连续动作',preview_shenzhen:'激光机关 · 冲刺破障',preview_snow:'轻微惯性 · 冰裂与雪球',preview_volcano:'落石预警 · 熔岩与火柱',preview_jiuzhaigou:'瀑布栈桥 · 水面跳台',preview_dreamPeak:'独立闯关 · 平台机关与检查点'});
Object.assign(I18N.en,{mapSelection:'Map selection',mapSelectionHint:'Choose an image to preview its route and mechanisms',endlessMode:'Endless run',endlessModeHint:'Six city and nature routes',challengeMode:'Challenge mode',challengeModeHint:'Hand-built platform stage',challengeBadge:'Standalone stage',parkourMode:'Endless run',stageMode:'Stage challenge',startChallenge:'Start challenge',preview_guangzhou:'River skyline · Drones and bridges',preview_shanghai:'Express train · Chained actions',preview_shenzhen:'Laser systems · Dash breaking',preview_snow:'Light inertia · Ice and snowballs',preview_volcano:'Rock warnings · Lava and flames',preview_jiuzhaigou:'Waterfalls · Bridges and platforms',preview_dreamPeak:'Standalone stage · Mechanisms and checkpoints'});
Object.assign(I18N.ru,{mapSelection:'Выбор карты',mapSelectionHint:'Выберите изображение маршрута и механизмов',endlessMode:'Бесконечный забег',endlessModeHint:'Шесть городских и природных трасс',challengeMode:'Режим испытания',challengeModeHint:'Авторский платформенный уровень',challengeBadge:'Отдельный уровень',parkourMode:'Бесконечный забег',stageMode:'Прохождение уровня',startChallenge:'Начать испытание',preview_guangzhou:'Река · Дроны и мосты',preview_shanghai:'Экспресс · Серии действий',preview_shenzhen:'Лазеры · Разрушение рывком',preview_snow:'Инерция · Лёд и снежки',preview_volcano:'Камни · Лава и огонь',preview_jiuzhaigou:'Водопады · Мосты и платформы',preview_dreamPeak:'Отдельный уровень · Механизмы и точки'});
Object.assign(I18N.zh,{tideCity:'潮汐沉没城',sandClock:'沙海时轮城',preview_tideCity:'潮位浮台 · 水闸与水流',preview_sandClock:'齿轮轨道 · 流沙追逐',tideFeatures:'潮位变化 · 浮力平台 · 水闸与锈蚀栅栏',sandFeatures:'时轮切换 · 齿轮轨道 · 流沙与沙浪',tideFreeze:'水闸已开启，潮位暂时冻结',grateBroken:'锈蚀栅栏已撞开',phaseShift:'时轮相位已切换',sandSink:'流沙平台正在下沉',leverBroken:'机械杠杆已复位'});
Object.assign(I18N.en,{tideCity:'Tidal Sunken City',sandClock:'Sandsea Clockwork City',preview_tideCity:'Rising tide · Sluices and currents',preview_sandClock:'Gear rails · Quicksand chase',tideFeatures:'Changing tide · Buoyant platforms · Sluices and rust grates',sandFeatures:'Time-wheel phases · Gear rails · Quicksand and sand wave',tideFreeze:'Sluice opened — tide temporarily frozen',grateBroken:'Rust grate smashed open',phaseShift:'Time-wheel phase shifted',sandSink:'Quicksand platform sinking',leverBroken:'Clockwork lever restored'});
Object.assign(I18N.ru,{tideCity:'Затонувший город приливов',sandClock:'Город песчаных часов',preview_tideCity:'Прилив · Шлюзы и течения',preview_sandClock:'Шестерни · Погоня по песку',tideFeatures:'Прилив · Плавучие платформы · Шлюзы и решётки',sandFeatures:'Фазы колеса · Шестерни · Зыбучий песок и волна',tideFreeze:'Шлюз открыт — прилив временно остановлен',grateBroken:'Ржавая решётка разбита',phaseShift:'Фаза колеса времени изменена',sandSink:'Платформа уходит в песок',leverBroken:'Механический рычаг восстановлен'});
Object.assign(I18N.zh,{selectOption:'选择{name}',selectClose:'关闭选择菜单',skinDesc_nova:'冷色科技装甲，稳定清晰的 NOVA 默认形态。',skinDesc_pulse:'脉冲能量沿装甲流动，拖尾节奏鲜明。',skinDesc_sunset:'暖色爆发装甲，冲刺时产生火花式拖尾。',skinDesc_prism:'棱镜折射装甲，紫蓝能量会分叉流动。',skinDesc_ace:'极光多色核心与专属装甲，代表最高级 NOVA 形态。',autoFullscreen:'开始时尝试全屏',enterFullscreen:'进入全屏',exitFullscreen:'退出全屏',fullscreenUnavailable:'当前浏览器不支持全屏，游戏仍可正常运行',installIosTitle:'添加 NOVA RUN 到主屏幕',installIosText:'在 Safari 中点击“分享”，再选择“添加到主屏幕”，即可获得更沉浸的独立应用体验。',gotIt:'知道了',dontRemind:'不再提示',updateReady:'发现新版本',updateNow:'刷新更新',later:'稍后'});
Object.assign(I18N.en,{selectOption:'Choose {name}',selectClose:'Close selection menu',skinDesc_nova:'Cool technical armor and the clear, stable default NOVA form.',skinDesc_pulse:'Pulse energy runs through the suit with a rhythmic trail.',skinDesc_sunset:'Warm burst armor with a spark-like dash trail.',skinDesc_prism:'Prismatic armor with split violet-blue energy trails.',skinDesc_ace:'An aurora core and unique armor for the highest NOVA tier.',autoFullscreen:'Try fullscreen on start',enterFullscreen:'Enter fullscreen',exitFullscreen:'Exit fullscreen',fullscreenUnavailable:'Fullscreen is unavailable; the game will continue normally',installIosTitle:'Add NOVA RUN to Home Screen',installIosText:'In Safari, tap Share and choose Add to Home Screen for an immersive standalone experience.',gotIt:'Got it',dontRemind:'Do not remind me',updateReady:'A new version is ready',updateNow:'Refresh now',later:'Later'});
Object.assign(I18N.ru,{selectOption:'Выбрать: {name}',selectClose:'Закрыть меню выбора',skinDesc_nova:'Холодная технологичная броня — стабильный базовый облик NOVA.',skinDesc_pulse:'Импульсная энергия проходит по броне и создаёт ритмичный след.',skinDesc_sunset:'Тёплая скоростная броня с искристым следом рывка.',skinDesc_prism:'Призматическая броня с раздвоенным фиолетово-синим следом.',skinDesc_ace:'Северное сияние в ядре и уникальная броня высшего уровня NOVA.',autoFullscreen:'Пробовать полный экран при старте',enterFullscreen:'Полный экран',exitFullscreen:'Выйти из полного экрана',fullscreenUnavailable:'Полный экран недоступен; игра продолжит работу',installIosTitle:'Добавить NOVA RUN на экран «Домой»',installIosText:'В Safari нажмите «Поделиться», затем «На экран Домой» для запуска как отдельного приложения.',gotIt:'Понятно',dontRemind:'Больше не показывать',updateReady:'Доступна новая версия',updateNow:'Обновить',later:'Позже'});
Object.assign(I18N.zh,{controlsHelp:'查看操作说明',closeSettingsResume:'关闭设置并继续游戏'});Object.assign(I18N.en,{controlsHelp:'Show controls',closeSettingsResume:'Close settings and resume'});Object.assign(I18N.ru,{controlsHelp:'Показать управление',closeSettingsResume:'Закрыть настройки и продолжить'});
Object.assign(I18N.zh,{appInstallTitle:'应用安装',appInstallCopy:'安装后可从桌面或主屏幕直接启动。',installNovaRun:'安装 NOVA RUN',addToHomeScreen:'添加到主屏幕',iosInstallShort:'点击后查看添加到主屏幕的方法。',installChecking:'正在检测安装状态…',installBrowserMenu:'可通过浏览器地址栏或菜单安装 NOVA RUN。',installAndroidMenu:'可通过浏览器菜单选择“安装应用”或“添加到主屏幕”。',installUnsupported:'请使用浏览器提供的安装或添加到主屏幕功能。',installed:'已安装',appInstalledCopy:'当前已作为独立应用运行。',updateReady:'NOVA RUN 有新版本',updateAfterRun:'NOVA RUN 有新版本，本局结束后更新',updateAfterRunAction:'本局结束后更新'});
Object.assign(I18N.en,{appInstallTitle:'App Install',appInstallCopy:'Launch directly from your desktop or Home Screen.',installNovaRun:'Install NOVA RUN',addToHomeScreen:'Add to Home Screen',iosInstallShort:'Open the steps for adding NOVA RUN to your Home Screen.',installChecking:'Checking installation status…',installBrowserMenu:'You can install NOVA RUN from the browser address bar or menu.',installAndroidMenu:'Use “Install app” or “Add to Home screen” from the browser menu.',installUnsupported:'Use the installation or Add to Home Screen option provided by your browser.',installed:'Installed',appInstalledCopy:'NOVA RUN is running as an installed app.',updateReady:'A new NOVA RUN version is available',updateAfterRun:'A new NOVA RUN version will install after this run',updateAfterRunAction:'Update after run'});
Object.assign(I18N.ru,{appInstallTitle:'Установка приложения',appInstallCopy:'Запускайте игру с рабочего стола или главного экрана.',installNovaRun:'Установить NOVA RUN',addToHomeScreen:'На экран «Домой»',iosInstallShort:'Открыть инструкцию добавления на главный экран.',installChecking:'Проверяем возможность установки…',installBrowserMenu:'NOVA RUN можно установить через адресную строку или меню браузера.',installAndroidMenu:'Выберите «Установить приложение» или «Добавить на главный экран» в меню браузера.',installUnsupported:'Используйте установку или добавление на главный экран в меню браузера.',installed:'Установлено',appInstalledCopy:'NOVA RUN запущена как установленное приложение.',updateReady:'Доступна новая версия NOVA RUN',updateAfterRun:'Новая версия NOVA RUN установится после забега',updateAfterRunAction:'Обновить после забега'});
globalThis.NovaRunI18n=Object.freeze(I18N);
})();
