(()=>{
'use strict';
const KEY='nova-run-profile-v1',CONFIG=globalThis.NovaRunConfig||{},CONTENT=CONFIG.CONTENT||{sceneUnlocks:{guangzhou:0},skins:[],achievements:[]};
const DEFAULT_SETTINGS=Object.freeze({language:'zh',theme:'dark',difficulty:'medium',scene:'guangzhou',skin:'nova',masterVolume:.8,musicEnabled:false,sfxEnabled:true,musicVolume:.34,sfxVolume:.72,vibration:true,shakeStrength:.7,reducedMotion:false,performanceMode:'auto',highContrast:false,touchOpacity:.9,showTutorial:true,autoFullscreen:true,fullscreenPromptDismissed:false,iosInstallDismissed:false});
const clone=value=>JSON.parse(JSON.stringify(value));
function dayKey(date=new Date()){const p=n=>String(n).padStart(2,'0');return`${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}`}
function dayHash(key){let h=2166136261;for(const ch of key){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function dailyTemplate(key=dayKey()){const h=dayHash(key);return{date:key,tasks:[{id:'distance',target:800+(h%5)*200,progress:0},{id:'perfect',target:3+((h>>>4)%4),progress:0},{id:'breaks',target:2+((h>>>8)%4),progress:0}]}}
function initial(){return{version:5,settings:{...DEFAULT_SETTINGS},stats:{distance:0,runs:0,maxCombo:0,collects:0,breaks:0,perfect:0,bestScore:0},challenge:{completed:[],records:{}},achievements:[],tutorialComplete:false,tutorialVersion:0,daily:dailyTemplate()}}
function migrateLegacy(profile){try{const ls=localStorage,s=profile.settings;const lang=ls.getItem('nova-run-language'),diff=ls.getItem('nova-run-difficulty'),scene=ls.getItem('nova-run-scene'),motion=ls.getItem('nova-run-reduced-motion');if(lang)s.language=lang;if(diff)s.difficulty=diff;if(scene)s.scene=scene;if(motion)s.reducedMotion=motion==='on';if(ls.getItem('nova-run-sound')==='off'){s.musicEnabled=false;s.sfxEnabled=false}}catch(e){}return profile}
function normalize(raw){const base=initial(),profile=raw&&typeof raw==='object'?raw:{};base.settings={...base.settings,...profile.settings};if((Number(profile.version)||0)<2)base.settings.musicEnabled=false;if(!CONTENT.skins.some(item=>item.id===base.settings.skin))base.settings.skin='nova';base.stats={...base.stats,...profile.stats};const challenge=profile.challenge&&typeof profile.challenge==='object'?profile.challenge:{};base.challenge.completed=Array.isArray(challenge.completed)?challenge.completed.filter(id=>typeof id==='string'):[];base.challenge.records=challenge.records&&typeof challenge.records==='object'?clone(challenge.records):{};base.achievements=Array.isArray(profile.achievements)?profile.achievements.filter(id=>typeof id==='string'):[];base.tutorialComplete=!!profile.tutorialComplete;base.tutorialVersion=Number(profile.tutorialVersion)||0;base.daily=profile.daily&&profile.daily.date===dayKey()?{...dailyTemplate(),...profile.daily,tasks:Array.isArray(profile.daily.tasks)?profile.daily.tasks:dailyTemplate().tasks}:dailyTemplate();return base}
let state;try{state=normalize(JSON.parse(localStorage.getItem(KEY)||'null'));if(!localStorage.getItem(KEY))state=migrateLegacy(state)}catch(e){state=initial()}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}return snapshot()}
function snapshot(){return clone(state)}
function settings(){return{...state.settings}}
function updateSettings(patch){state.settings={...state.settings,...patch};return save().settings}
function setTutorialComplete(done=true){state.tutorialComplete=!!done;if(done)state.tutorialVersion=1;save()}
function ensureDaily(){if(state.daily.date!==dayKey()){state.daily=dailyTemplate();save()}return clone(state.daily)}
function unlockedScenes(){const out=[];for(const scene of CONFIG.SCENES||Object.keys(CONTENT.sceneUnlocks)){const rule=CONTENT.sceneUnlocks[scene];if(typeof rule==='number'&&state.stats.distance>=rule)out.push(scene);else if(typeof rule==='string'&&rule.startsWith('runs:')&&state.stats.runs>=Number(rule.slice(5)))out.push(scene);else if(rule&&typeof rule==='object'&&rule.complete&&state.challenge.completed.includes(rule.complete))out.push(scene)}return out}
function challengeRecord(id){const record=state.challenge.records[id]||{},badges=record.badges&&typeof record.badges==='object'?record.badges:{};return{bestScore:Number(record.bestScore)||0,bestTime:Number(record.bestTime)||0,minDeaths:Number.isFinite(record.minDeaths)?record.minDeaths:null,bestGrade:typeof record.bestGrade==='string'?record.bestGrade:'',badges:{allCollects:!!badges.allCollects,noDeaths:!!badges.noDeaths,time:!!badges.time},completed:state.challenge.completed.includes(id)}}
function completeChallenge(id,summary={}){if(!(CONFIG.CHALLENGE_SCENES||[]).includes(id))return{newlyCompleted:false,record:challengeRecord(id)};const old=challengeRecord(id),score=Math.max(0,Math.floor(summary.score||0)),time=Math.max(0,Number(summary.time)||0),deaths=Math.max(0,Math.floor(summary.deaths||0)),grade=String(summary.grade||''),rank={S:4,A:3,B:2,C:1},newlyCompleted=!old.completed,badges={allCollects:old.badges.allCollects||!!summary.allCollects,noDeaths:old.badges.noDeaths||deaths===0,time:old.badges.time||!!summary.timeBadge};if(newlyCompleted)state.challenge.completed.push(id);state.challenge.records[id]={bestScore:Math.max(old.bestScore,score),bestTime:old.bestTime>0&&time>0?Math.min(old.bestTime,time):Math.max(old.bestTime,time),minDeaths:old.minDeaths==null?deaths:Math.min(old.minDeaths,deaths),bestGrade:(rank[grade]||0)>(rank[old.bestGrade]||0)?grade:old.bestGrade,badges};save();return{newlyCompleted,record:challengeRecord(id)}}
function unlockedSkins(){return CONTENT.skins.filter(item=>(!item.distance||state.stats.distance>=item.distance)&&(!item.collects||state.stats.collects>=item.collects)&&(!item.combo||state.stats.maxCombo>=item.combo)).map(item=>item.id)}
function achievementProgress(item){if(item.type==='daily')return state.daily.tasks.filter(task=>task.progress>=task.target).length;if(item.type==='combo')return state.stats.maxCombo||0;return state.stats[item.type]||0}
function unlockAchievements(){const fresh=[];for(const item of CONTENT.achievements){if(state.achievements.includes(item.id))continue;if(achievementProgress(item)>=item.target){state.achievements.push(item.id);fresh.push(item.id)}}return fresh}
function beginRun(){state.stats.runs++;const fresh=unlockAchievements();save();return{fresh,runNumber:state.stats.runs}}
function finishRun(summary={}){ensureDaily();const distance=Math.max(0,Math.floor(summary.distance||0)),collects=Math.max(0,Math.floor(summary.collects||0)),breaks=Math.max(0,Math.floor(summary.breaks||0)),perfect=Math.max(0,Math.floor(summary.perfect||0)),combo=Math.max(0,Math.floor(summary.maxCombo||0)),score=Math.max(0,Math.floor(summary.score||0));state.stats.distance+=distance;state.stats.collects+=collects;state.stats.breaks+=breaks;state.stats.perfect+=perfect;state.stats.maxCombo=Math.max(state.stats.maxCombo,combo);state.stats.bestScore=Math.max(state.stats.bestScore,score);for(const task of state.daily.tasks){if(task.id==='distance')task.progress+=distance;if(task.id==='perfect')task.progress+=perfect;if(task.id==='breaks')task.progress+=breaks;task.progress=Math.min(task.target,task.progress)}const fresh=unlockAchievements(),beforeScenes=new Set(summary.unlockedScenesBefore||[]),beforeSkins=new Set(summary.unlockedSkinsBefore||[]),newScenes=unlockedScenes().filter(id=>!beforeScenes.has(id)),newSkins=unlockedSkins().filter(id=>!beforeSkins.has(id));save();return{fresh,newScenes,newSkins,profile:snapshot()}}
function clearAll(){try{for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key&&key.startsWith('nova-run'))localStorage.removeItem(key)}}catch(e){}state=initial();return snapshot()}
globalThis.NovaRunStorage=Object.freeze({DEFAULT_SETTINGS,dayKey,dailyTemplate,snapshot,settings,updateSettings,setTutorialComplete,ensureDaily,unlockedScenes,unlockedSkins,challengeRecord,completeChallenge,beginRun,finishRun,clearAll});
})();
