(()=>{
'use strict';
function create(options){
  const {root,storage,audio,tr,actions}=options,q=selector=>root.querySelector(selector),qa=selector=>Array.from(root.querySelectorAll(selector));
  const settingsPanel=q('.nr-toolbar'),settingsBackdrop=q('[data-settings-backdrop]'),settingsScroll=q('.nr-settings-scroll'),profilePanel=q('[data-profile-panel]'),tutorialPanel=q('[data-tutorial]'),resultsPanel=q('[data-results]'),sharePanel=q('[data-share-panel]'),confirmPanel=q('[data-confirm]'),toastPanel=q('[data-toast]'),installPanel=q('[data-ios-install]'),appInstall=q('[data-app-install]'),appInstallAction=q('[data-app-install-action]'),appInstallCopy=q('[data-app-install-copy]'),updatePanel=q('[data-update-prompt]'),updateMessage=q('[data-update-message]');
  const scenePicker=q('[data-scene-picker]'),difficultyField=q('.nr-difficulty-setting'),skinSelect=q('[data-setting="skin"]'),content=globalThis.NovaRunConfig.CONTENT,PlayerRenderer=globalThis.NovaRunPlayerRenderer;
  let tutorialIndex=-1,lastSummary=null,toastTimer=0,sceneMode='runner',selectMenu=null,currentSettingsPage='map',modalWasOpen=false,settingsHistoryToken='',ignoreSettingsPop=false;
  const tutorialSteps=[['jump','tutorialJumpTitle','tutorialJumpText'],['slide','tutorialSlideTitle','tutorialSlideText'],['doubleJump','tutorialDoubleTitle','tutorialDoubleText'],['dashBreak','tutorialDashTitle','tutorialDashText'],['collect','tutorialCollectTitle','tutorialCollectText']];
    const suppressButtonLongPress=event=>{
    const target=event.target instanceof Element
      ? event.target
      : null;

    if(target&&target.closest('button')){
      event.preventDefault();
    }
  };

  for(const eventName of [
    'contextmenu',
    'selectstart',
    'dragstart'
  ]){
    root.addEventListener(eventName,suppressButtonLongPress);
  }
  const safe=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function toast(text){clearTimeout(toastTimer);toastPanel.textContent=text;toastPanel.hidden=false;toastTimer=setTimeout(()=>{toastPanel.hidden=true},2600)}
  function modalState({resume=false}={}){const open=root.classList.contains('settings-open')||!profilePanel.hidden||!resultsPanel.hidden||!sharePanel.hidden||!confirmPanel.hidden||!installPanel.hidden||!!selectMenu?.open,changed=open!==modalWasOpen;root.classList.toggle('modal-open',open);modalWasOpen=open;if(changed&&open&&actions.modalOpen)actions.modalOpen();else if(changed&&!open&&actions.modalClose)actions.modalClose(!!resume)}
  function touchHistoryEnabled(){return (navigator.maxTouchPoints||0)>0||matchMedia('(pointer:coarse)').matches}
  function pushSettingsHistory(){if(settingsHistoryToken||!touchHistoryEnabled())return;try{settingsHistoryToken=`nr-settings-${Date.now().toString(36)}`;history.pushState({...history.state,nrSettingsToken:settingsHistoryToken},document.title)}catch(error){settingsHistoryToken=''}}
  function clearSettingsHistory(consume=true){if(!settingsHistoryToken)return;try{if(history.state&&history.state.nrSettingsToken===settingsHistoryToken){if(consume){ignoreSettingsPop=true;history.back()}else{const state={...history.state};delete state.nrSettingsToken;history.replaceState(state,document.title)}}}catch(error){}settingsHistoryToken=''}
  function setSettingsPage(page){
    currentSettingsPage=['map','character','settings'].includes(page)?page:'map';
    selectMenu?.close('page-change');
    qa('.is-choosing').forEach(card=>card.classList.remove('is-choosing'));
    root.dataset.settingsPage=currentSettingsPage;
    qa('[data-settings-section]').forEach(section=>section.hidden=section.dataset.settingsSection!==currentSettingsPage);
    qa('[data-settings-page]').forEach(tab=>tab.setAttribute('aria-selected',String(tab.dataset.settingsPage===currentSettingsPage)));
    settingsScroll.scrollTop=0;
    if(currentSettingsPage==='character')renderSkins();
  }
  function openSettings(page){renderSettings();root.classList.add('settings-open');settingsPanel.setAttribute('aria-hidden','false');profilePanel.hidden=true;setSettingsPage(page||root.dataset.settingsPage||'map');pushSettingsHistory();modalState()}
  function closeSettings({resume=false,consumeHistory=true}={}){selectMenu?.close('settings-close');qa('.is-choosing').forEach(card=>card.classList.remove('is-choosing'));root.classList.remove('settings-open');settingsPanel.setAttribute('aria-hidden','true');clearSettingsHistory(consumeHistory);modalState({resume})}
  function updateSceneFocus(card){if(!card)return;const id=card.dataset.sceneValue,image=card.querySelector('img'),preview=tr(`preview_${id}`),parts=preview.split(/\s*[·•]\s*/).filter(Boolean);q('[data-scene-focus-image]').src=image.src;q('[data-scene-focus-name]').textContent=tr(id);q('[data-scene-focus-copy]').textContent=preview;q('[data-scene-focus-tags]').innerHTML=parts.slice(0,3).map(part=>`<b>${safe(part)}</b>`).join('')}
  function setSceneMode(mode){sceneMode=mode==='challenge'?'challenge':'runner';qa('[data-scene-tab]').forEach(tab=>tab.setAttribute('aria-selected',String(tab.dataset.sceneTab===sceneMode)));let focus=null;qa('[data-scene-card]').forEach(card=>{card.hidden=card.dataset.sceneMode!==sceneMode;if(!card.hidden&&(card.classList.contains('is-selected')||!focus))focus=card});updateSceneFocus(focus)}
  function unlockNeed(rule){return typeof rule==='number'?`${rule}m`:typeof rule==='string'?rule.replace('runs:','×'):rule&&rule.complete?`✓ ${tr(rule.complete)}`:''}
  function skinNeed(item){return item.distance?`${item.distance}m`:item.collects?`${item.collects} ${tr('totalCollects')}`:item.combo?`×${item.combo}`:''}
  function previewTheme(){const css=getComputedStyle(root),value=(name,fallback)=>css.getPropertyValue(name).trim()||fallback;return{bg:value('--background','#181919'),card:value('--card','#2d2e2d'),fg:value('--foreground','#f8f2e9'),one:value('--viz-series-1','#83c3ff'),two:value('--viz-series-2','#d97753'),three:value('--viz-series-3','#74d58b')}}
  function renderSkinCanvas(canvas,skin,width,height,large=false){const dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);canvas.style.aspectRatio=`${width}/${height}`;const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);PlayerRenderer.drawPreview(ctx,{skin,theme:previewTheme(),width,height,reducedMotion:storage.settings().reducedMotion,dash:large})}
  function renderSkins(){
    const settings=storage.settings(),unlocked=storage.unlockedSkins(),selected=unlocked.includes(settings.skin)?settings.skin:'nova';
    skinSelect.innerHTML=content.skins.map(item=>`<option value="${safe(item.id)}"${unlocked.includes(item.id)?'':' disabled'}>${safe(tr(item.nameKey||`skin_${item.id}`))}${unlocked.includes(item.id)?'':` · ${safe(skinNeed(item))}`}</option>`).join('');
    skinSelect.value=selected;
    for(const card of qa('[data-skin-card]')){
      const item=content.skins.find(skin=>skin.id===card.dataset.skinCard);if(!item)continue;
      const open=unlocked.includes(item.id),active=item.id===selected,name=tr(item.nameKey||`skin_${item.id}`),description=tr(item.descriptionKey||`skinDesc_${item.id}`);
      card.disabled=false;card.dataset.locked=String(!open);card.setAttribute('aria-selected',String(active));card.setAttribute('aria-label',open?name:`${name} · ${tr('locked')} · ${skinNeed(item)}`);card.classList.toggle('is-selected',active);card.querySelector('span').textContent=name;card.querySelector('small').textContent=open?description:`${tr('locked')} · ${skinNeed(item)}`;card.querySelector('i').dataset.state=active?'selected':open?'':'locked';card.querySelector('i').textContent='';renderSkinCanvas(card.querySelector('canvas'),item,180,128,false)
    }
    const active=content.skins.find(item=>item.id===selected)||content.skins[0],signature=`NOVA SIGNATURE · ${String(content.skins.indexOf(active)+1).padStart(2,'0')}`;q('[data-skin-focus-name]').textContent=tr(active.nameKey||`skin_${active.id}`);q('[data-skin-focus-description]').textContent=tr(active.descriptionKey||`skinDesc_${active.id}`);q('[data-skin-focus-unlock]').textContent=unlocked.includes(active.id)?signature:`${tr('locked')} · ${skinNeed(active)}`;renderSkinCanvas(q('[data-skin-focus-canvas]'),active,420,260,true)
  }
  function renderSettings(){
    const state=storage.snapshot(),settings=state.settings,unlocked=storage.unlockedScenes(),challengeIds=globalThis.NovaRunConfig.CHALLENGE_SCENES||[],completed=new Set((state.challenge&&state.challenge.completed)||[]);
    qa('[data-setting]').forEach(input=>{const key=input.dataset.setting;if(key==='scene'||key==='skin')return;if(input.type==='checkbox')input.checked=key==='motion'?!!settings.reducedMotion:!!settings[key];else input.value=settings[key]});
    qa('[data-setting="scene"] option').forEach(option=>{const open=unlocked.includes(option.value)||option.value===settings.scene,need=unlockNeed(content.sceneUnlocks[option.value]);option.disabled=!open;option.textContent=`${tr(option.value)}${open?'':` · ${tr('locked')} · ${need}`}`});
    qa('[data-scene-card]').forEach(card=>{const id=card.dataset.sceneValue,open=unlocked.includes(id)||id===settings.scene,need=unlockNeed(content.sceneUnlocks[id]),lock=card.querySelector('[data-scene-lock]'),complete=card.querySelector('[data-scene-complete]');card.disabled=false;card.dataset.locked=String(!open);card.dataset.unlockText=need;card.setAttribute('aria-label',open?tr(id):`${tr(id)} · ${tr('locked')} · ${need}`);card.setAttribute('aria-pressed',String(id===settings.scene));card.classList.toggle('is-selected',id===settings.scene);lock.hidden=open;lock.textContent=open?'':need;if(complete)complete.hidden=!completed.has(id)});
    setSceneMode(challengeIds.includes(settings.scene)?'challenge':'runner');renderSkins();selectMenu?.refresh();
  }
  function renderProfile(){const state=storage.snapshot(),stats=state.stats,daily=storage.ensureDaily(),achievementIds=new Set(state.achievements);q('[data-profile-stats]').innerHTML=[['totalDistance',`${Math.floor(stats.distance)} m`],['totalRuns',stats.runs],['highestCombo',`×${stats.maxCombo}`],['totalCollects',stats.collects]].map(([key,value])=>`<div class="nr-stat"><span>${safe(tr(key))}</span><strong>${safe(value)}</strong></div>`).join('');q('[data-daily-list]').innerHTML=daily.tasks.map(task=>`<div class="nr-daily-item"><span>${safe(tr(`daily_${task.id}`,{target:task.target}))}</span><b>${task.progress}/${task.target}</b><div class="nr-daily-bar"><i style="width:${Math.min(100,task.progress/task.target*100)}%"></i></div></div>`).join('');q('[data-achievement-list]').innerHTML=content.achievements.map(item=>`<span class="nr-achievement ${achievementIds.has(item.id)?'unlocked':''}">${achievementIds.has(item.id)?'✓ ':'○ '}${safe(tr(`achievement_${item.id}`))}</span>`).join('')}
  function openProfile(){renderProfile();profilePanel.hidden=false;closeSettings({resume:false});modalState()}
  function closeProfile(resume=false){profilePanel.hidden=true;modalState({resume})}
  function drawTutorial(){const step=tutorialSteps[tutorialIndex];if(!step){tutorialPanel.hidden=true;return}q('[data-tutorial-count]').textContent=`${tutorialIndex+1} / ${tutorialSteps.length}`;q('[data-tutorial-title]').textContent=tr(step[1]);q('[data-tutorial-text]').textContent=tr(step[2]);tutorialPanel.hidden=false}
  function startTutorial(){const state=storage.snapshot();if(!state.settings.showTutorial||state.tutorialComplete)return false;tutorialIndex=0;drawTutorial();return true}
  function tutorialSignal(action){if(tutorialIndex<0)return false;const step=tutorialSteps[tutorialIndex];if(!step||step[0]!==action)return false;tutorialIndex++;if(tutorialIndex>=tutorialSteps.length){storage.setTutorialComplete(true);tutorialIndex=-1;tutorialPanel.hidden=true;toast(tr('tutorialComplete'));return true}drawTutorial();return true}
  function skipTutorial(){storage.setTutorialComplete(true);tutorialIndex=-1;tutorialPanel.hidden=true;toast(tr('tutorialSkipped'));modalState()}
  function hideResults(){resultsPanel.hidden=true;sharePanel.hidden=true;modalState()}
  function resetTransient(){clearTimeout(toastTimer);toastTimer=0;toastPanel.hidden=true;tutorialIndex=-1;tutorialPanel.hidden=true;lastSummary=null;resultsPanel.hidden=true;sharePanel.hidden=true;confirmPanel.hidden=true;selectMenu?.close('reset',false);qa('.is-choosing').forEach(card=>card.classList.remove('is-choosing'));closeSettings({resume:false,consumeHistory:false});closeProfile(false);modalState()}
  function showResults(summary){const firstShow=resultsPanel.hidden;lastSummary=summary;sharePanel.hidden=true;closeSettings({resume:false,consumeHistory:false});closeProfile(false);tutorialIndex=-1;tutorialPanel.hidden=true;q('[data-result-record]').textContent=summary.newBest?tr('newBest'):'';q('[data-result-score]').textContent=summary.challenge?`${summary.challenge.grade} · ${tr('points',{score:summary.score})}`:tr('points',{score:summary.score});const rows=summary.challenge?[['challengeGrade',summary.challenge.grade],['completionTime',`${summary.challenge.time.toFixed(1)} s`],['deaths',summary.challenge.deaths],['totalCollects',`${summary.challenge.collects}/${summary.challenge.total}`],['hiddenRoute',summary.challenge.hidden?'✓':'—'],['scene',tr(summary.scene)]]:[['distance',`${summary.distance} m`],['bestLabel',summary.best],['highestCombo',`×${summary.maxCombo}`],['totalCollects',summary.collects],['scene',tr(summary.scene)],['difficulty',tr(summary.difficulty)]];q('[data-result-grid]').innerHTML=rows.map(([key,value])=>`<div class="nr-result-item"><span>${safe(tr(key))}</span><strong>${safe(value)}</strong></div>`).join('')+(summary.challenge?`<div class="nr-result-badges"><b class="${summary.challenge.allCollects?'earned':''}">${safe(tr('badgeAllCollects'))}</b><b class="${summary.challenge.deaths===0?'earned':''}">${safe(tr('badgeNoDeaths'))}</b><b class="${summary.challenge.timeBadge?'earned':''}">${safe(tr('badgeTime'))}</b></div>`:'');resultsPanel.hidden=false;modalState();if(firstShow&&summary.newBest)audio.sfx('newRecord');if(firstShow&&summary.unlockText)toast(summary.unlockText)}
  function copyText(text){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(text);return new Promise((resolve,reject)=>{const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{document.execCommand('copy')?resolve():reject(new Error('copy failed'))}catch(error){reject(error)}finally{area.remove()}})}
  function openShareFallback(text){q('[data-share-text]').value=text;sharePanel.hidden=false;modalState();q('[data-share-text]').focus();q('[data-share-text]').select()}
  async function share(){if(!lastSummary)return;const data={title:'NOVA RUN',text:lastSummary.shareText,url:lastSummary.challengeUrl},text=`${data.text}\n${data.url}`,canSystemShare=(location.protocol==='https:'||location.protocol==='http:')&&typeof navigator.share==='function';if(!canSystemShare){openShareFallback(text);return}try{await navigator.share(data)}catch(error){if(error&&error.name==='AbortError')return;openShareFallback(text)}}
  function applyLanguage(){qa('[data-i18n]').forEach(el=>el.textContent=tr(el.dataset.i18n));settingsBackdrop.setAttribute('aria-label',tr('closeSettingsResume'));renderSettings();if(!profilePanel.hidden)renderProfile();if(tutorialIndex>=0)drawTutorial();if(lastSummary&&!resultsPanel.hidden)showResults(lastSummary);selectMenu?.refresh()}
  function syncPause(){modalState()}
  function showUpdate(info={}){const key=info.deferred?'updateAfterRun':'updateReady';updateMessage.dataset.i18n=key;updateMessage.textContent=tr(key);q('[data-update-now]').dataset.i18n=info.deferred?'updateAfterRunAction':'updateNow';q('[data-update-now]').textContent=tr(info.deferred?'updateAfterRunAction':'updateNow');updatePanel.hidden=false}
  function setInstallState(info={}){const status=info.status||'checking';appInstall.hidden=false;appInstall.dataset.installMode=status;appInstallAction.disabled=status==='installed';appInstallAction.hidden=false;if(status==='installed'){appInstallAction.dataset.i18n='installed';appInstallAction.textContent=tr('installed');appInstallCopy.dataset.i18n='appInstalledCopy';appInstallCopy.textContent=tr('appInstalledCopy')}else if(status==='ios-guide'){appInstallAction.dataset.i18n='addToHomeScreen';appInstallAction.textContent=tr('addToHomeScreen');appInstallCopy.dataset.i18n='iosInstallShort';appInstallCopy.textContent=tr('iosInstallShort')}else if(status==='installable'){appInstallAction.dataset.i18n='installNovaRun';appInstallAction.textContent=tr('installNovaRun');appInstallCopy.dataset.i18n='appInstallCopy';appInstallCopy.textContent=tr('appInstallCopy')}else{appInstallAction.hidden=true;const key=status==='android-menu'?'installAndroidMenu':status==='browser-menu'?'installBrowserMenu':status==='unsupported'?'installUnsupported':'installChecking';appInstallCopy.dataset.i18n=key;appInstallCopy.textContent=tr(key)}}
  function maybeShowIosInstall(platform){setInstallState(platform?.installState?.()||{})}

  function handleBack(){if(selectMenu?.open){selectMenu.close('back');return true}if(!confirmPanel.hidden){confirmPanel.hidden=true;modalState();return true}if(!sharePanel.hidden){sharePanel.hidden=true;modalState();return true}if(root.classList.contains('settings-open')){closeSettings({resume:true});return true}if(!profilePanel.hidden){closeProfile(true);return true}return false}
  qa('[data-open-settings]').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();openSettings()}));
  q('[data-close-settings]').addEventListener('click',()=>closeSettings({resume:true}));settingsBackdrop.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();closeSettings({resume:true})});qa('[data-open-profile]').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();openProfile()}));q('[data-close-profile]').addEventListener('click',()=>closeProfile(true));qa('[data-skip-tutorial]').forEach(button=>button.addEventListener('click',skipTutorial));
  qa('[data-settings-page]').forEach(tab=>tab.addEventListener('click',event=>{event.stopPropagation();setSettingsPage(tab.dataset.settingsPage)}));
  qa('[data-scene-tab]').forEach(tab=>tab.addEventListener('click',event=>{event.stopPropagation();setSceneMode(tab.dataset.sceneTab)}));
  qa('[data-scene-card]').forEach(card=>card.addEventListener('click',event=>{event.stopPropagation();card.classList.add('is-choosing');updateSceneFocus(card);const release=()=>requestAnimationFrame(()=>{card.classList.remove('is-choosing');if(matchMedia('(pointer:coarse)').matches)card.blur()});if(card.dataset.locked==='true'){toast(`${tr('locked')} · ${card.dataset.unlockText||''}`);release();return}if(actions.sceneSelect&&actions.sceneSelect(card.dataset.sceneValue))renderSettings();release()}));
  qa('[data-skin-card]').forEach(card=>card.addEventListener('click',event=>{event.stopPropagation();const id=card.dataset.skinCard;if(card.dataset.locked==='true'){const item=content.skins.find(skin=>skin.id===id);toast(`${tr('locked')} · ${skinNeed(item)}`);return}skinSelect.value=id;skinSelect.dispatchEvent(new Event('input',{bubbles:true}));skinSelect.dispatchEvent(new Event('change',{bubbles:true}))}));
  qa('[data-setting]').forEach(input=>{const key=input.dataset.setting;if(['language','difficulty','scene','motion'].includes(key))return;const read=()=>input.type==='checkbox'?input.checked:input.type==='range'?Number(input.value):input.value;if(input.type==='range'){input.addEventListener('input',()=>{if(actions.previewSetting)actions.previewSetting(key,read())});input.addEventListener('change',()=>actions.setting(key,read()))}else input.addEventListener('change',()=>{actions.setting(key,read());renderSettings()})});
  q('[data-clear-save]').addEventListener('click',()=>{confirmPanel.hidden=false;modalState()});qa('[data-confirm-cancel]').forEach(button=>button.addEventListener('click',()=>{confirmPanel.hidden=true;modalState()}));q('[data-confirm-clear]').addEventListener('click',()=>{storage.clearAll();location.reload()});
  qa('[data-share-close]').forEach(button=>button.addEventListener('click',()=>{sharePanel.hidden=true;modalState()}));q('[data-share-copy]').addEventListener('click',async()=>{const text=q('[data-share-text]').value;try{await copyText(text);toast(tr('scoreCopied'))}catch(error){q('[data-share-text]').focus();q('[data-share-text]').select();toast(tr('manualCopySelected'))}});
  qa('[data-result-action]').forEach(button=>button.addEventListener('click',()=>{const action=button.dataset.resultAction;if(action==='share')share();else{hideResults();actions[action]()}}));q('[data-result-close]').addEventListener('click',()=>{hideResults();actions.menu()});
  q('[data-fullscreen-enter]').addEventListener('click',()=>actions.enterFullscreen());q('[data-fullscreen-exit]').addEventListener('click',()=>actions.exitFullscreen());
  appInstallAction.addEventListener('click',async()=>{if(appInstall.dataset.installMode==='ios-guide'){installPanel.hidden=false;modalState();return}if(appInstall.dataset.installMode!=='installable')return;const state=await actions.installApp?.();if(state)setInstallState(state)});
  function dismissIosInstall(){storage.updateSettings({iosInstallDismissed:true});installPanel.hidden=true;modalState()}
  q('[data-ios-install-ok]').addEventListener('click',dismissIosInstall);q('[data-ios-install-dismiss]').addEventListener('click',dismissIosInstall);
  q('[data-update-now]').addEventListener('click',()=>{actions.applyUpdate();updatePanel.hidden=true});q('[data-update-later]').addEventListener('click',()=>{updatePanel.hidden=true});
  addEventListener('popstate',()=>{if(ignoreSettingsPop){ignoreSettingsPop=false;return}if(!settingsHistoryToken||history.state&&history.state.nrSettingsToken===settingsHistoryToken||selectMenu?.open)return;if(root.classList.contains('settings-open'))closeSettings({resume:true,consumeHistory:false})});
  selectMenu=globalThis.NovaRunSelectMenu.create({root,storage,tr,onOpen:()=>modalState(),onClose:()=>modalState()});
  setSettingsPage('map');renderSettings();
  return Object.freeze({applyLanguage,renderSettings,renderProfile,renderSkins,openSettings,closeSettings,openProfile,closeProfile,handleBack,startTutorial,tutorialSignal,skipTutorial,showResults,hideResults,resetTransient,toast,syncPause,showUpdate,setInstallState,maybeShowIosInstall,get tutorialActive(){return tutorialIndex>=0}})
}
globalThis.NovaRunUI=Object.freeze({create});
})();
